
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Mozu.Api.Contracts.Core.ThirdParty;

namespace Mozu.Api.Contracts.SiteSettings.Application
{
		public class Capability
		{
			public List<string> ActiveCreditTypes { get; set; }

			public List<string> ActiveShoppingCountries { get; set; }

			public string CapabilityMode { get; set; }

			public string CapabilityType { get; set; }

			public bool? Enabled { get; set; }

			public string Id { get; set; }

			public bool? Initialized { get; set; }

			public int? ScopeId { get; set; }

			public string ScopeType { get; set; }

			public List<ActiveShippingCountry> ActiveShippingCountries { get; set; }

			public List<OperationUrl> OperationUrls { get; set; }

			public List<InitializablePropertyValue> SupportedCreditTypes { get; set; }

			public List<InitializableShippingCountryPropertyValue> SupportedShippingCountries { get; set; }

			public List<InitializablePropertyValue> SupportedShoppingCountries { get; set; }

		}

}