
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Mozu.Api.Security;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;

namespace Mozu.Api.Resources.Commerce.Carts
{
	/// <summary>
	/// Use the Cart Messages resource to retrieve messages for live carts that the system logs when a product's price or inventory level changes.
	/// </summary>
	public partial class ChangeMessageResource  	{
		///
		/// <see cref="Mozu.Api.ApiContext"/>
		///
		private readonly IApiContext _apiContext;

		
		public ChangeMessageResource(IApiContext apiContext) 
		{
			_apiContext = apiContext;
		}

		public ChangeMessageResource CloneWithApiContext(Action<IApiContext> contextModification) 
		{
			return new ChangeMessageResource(_apiContext.CloneWith(contextModification));
		}

				
		/// <summary>
		/// Retrieves the messages associated with the current shopper's cart.
		/// </summary>
		/// <param name="responseFields">Use this field to include those fields which are not included by default.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.CommerceRuntime.Carts.CartChangeMessageCollection"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var changemessage = new ChangeMessage();
		///   var cartChangeMessageCollection = changemessage.GetMessages( responseFields);
		/// </code>
		/// </example>
		[Obsolete("This method is obsolete; use the async method instead")]
		public virtual Mozu.Api.Contracts.CommerceRuntime.Carts.CartChangeMessageCollection GetMessages(string responseFields =  null)
		{
			MozuClient<Mozu.Api.Contracts.CommerceRuntime.Carts.CartChangeMessageCollection> response;
			var client = Mozu.Api.Clients.Commerce.Carts.ChangeMessageClient.GetMessagesClient( responseFields);
			client.WithContext(_apiContext);
			response = client.Execute();
			return response.Result();

		}

		/// <summary>
		/// Retrieves the messages associated with the current shopper's cart.
		/// </summary>
		/// <param name="responseFields">Use this field to include those fields which are not included by default.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.CommerceRuntime.Carts.CartChangeMessageCollection"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var changemessage = new ChangeMessage();
		///   var cartChangeMessageCollection = await changemessage.GetMessagesAsync( responseFields);
		/// </code>
		/// </example>
		public virtual async Task<Mozu.Api.Contracts.CommerceRuntime.Carts.CartChangeMessageCollection> GetMessagesAsync(string responseFields =  null)
		{
			MozuClient<Mozu.Api.Contracts.CommerceRuntime.Carts.CartChangeMessageCollection> response;
			var client = Mozu.Api.Clients.Commerce.Carts.ChangeMessageClient.GetMessagesClient( responseFields);
			client.WithContext(_apiContext);
			response = await client.ExecuteAsync();
			return await response.ResultAsync();

		}

		/// <summary>
		/// Deletes all messages associated with the cart of the current shopper.
		/// </summary>
		/// <returns>
		/// 
		/// </returns>
		/// <example>
		/// <code>
		///   var changemessage = new ChangeMessage();
		///   changemessage.RemoveAllMessages();
		/// </code>
		/// </example>
		[Obsolete("This method is obsolete; use the async method instead")]
		public virtual void RemoveAllMessages()
		{
			MozuClient response;
			var client = Mozu.Api.Clients.Commerce.Carts.ChangeMessageClient.RemoveAllMessagesClient();
			client.WithContext(_apiContext);
			response = client.Execute();

		}

		/// <summary>
		/// Deletes all messages associated with the cart of the current shopper.
		/// </summary>
		/// <returns>
		/// 
		/// </returns>
		/// <example>
		/// <code>
		///   var changemessage = new ChangeMessage();
		///   await changemessage.RemoveAllMessagesAsync();
		/// </code>
		/// </example>
		public virtual async Task RemoveAllMessagesAsync()
		{
			MozuClient response;
			var client = Mozu.Api.Clients.Commerce.Carts.ChangeMessageClient.RemoveAllMessagesClient();
			client.WithContext(_apiContext);
			response = await client.ExecuteAsync();

		}

		/// <summary>
		/// Removes a single message associated with the cart of the current shopper.
		/// </summary>
		/// <param name="messageId">Identifier of the message to remove from the cart.</param>
		/// <returns>
		/// 
		/// </returns>
		/// <example>
		/// <code>
		///   var changemessage = new ChangeMessage();
		///   changemessage.RemoveMessage( messageId);
		/// </code>
		/// </example>
		[Obsolete("This method is obsolete; use the async method instead")]
		public virtual void RemoveMessage(string messageId)
		{
			MozuClient response;
			var client = Mozu.Api.Clients.Commerce.Carts.ChangeMessageClient.RemoveMessageClient( messageId);
			client.WithContext(_apiContext);
			response = client.Execute();

		}

		/// <summary>
		/// Removes a single message associated with the cart of the current shopper.
		/// </summary>
		/// <param name="messageId">Identifier of the message to remove from the cart.</param>
		/// <returns>
		/// 
		/// </returns>
		/// <example>
		/// <code>
		///   var changemessage = new ChangeMessage();
		///   await changemessage.RemoveMessageAsync( messageId);
		/// </code>
		/// </example>
		public virtual async Task RemoveMessageAsync(string messageId)
		{
			MozuClient response;
			var client = Mozu.Api.Clients.Commerce.Carts.ChangeMessageClient.RemoveMessageClient( messageId);
			client.WithContext(_apiContext);
			response = await client.ExecuteAsync();

		}


	}

}


