
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Contracts.ProductRuntime
{
		///
		///	Validates the attribute configured for the customer in the storefront against the attribute configured in Mozu admin.
		///
		public class AttributeValidation
		{
			///
			///The maximum date allowed including month, day, and year. System-supplied and read-only.
			///
			public DateTime? MaxDateValue { get; set; }

			///
			///The maximum number that can be entered as a value for an extensible attribute.
			///
			public double MaxNumericValue { get; set; }

			///
			///The maximum character length possible for a string value entered for an extensible attribute.
			///
			public int? MaxStringLength { get; set; }

			///
			///The minimum date allowed including month, day, and year. System-supplied and read-only.
			///
			public DateTime? MinDateValue { get; set; }

			///
			///The minimum numeric value required to validate an extensible attribute.
			///
			public double MinNumericValue { get; set; }

			///
			///The minimum character length possible for a string value entered for an extensible attribute.
			///
			public int? MinStringLength { get; set; }

			///
			///Regular expression used to process and validate an extensible attribute value that require special formatting, such as phone numbers.
			///
			public string RegularExpression { get; set; }

		}

}