
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mozu.Api.Urls.Commerce.Customer
{
	public partial class CustomerAuthTicketUrl 
	{

		/// <summary>
        /// Get Resource Url for CreateAnonymousShopperAuthTicket
        /// </summary>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl CreateAnonymousShopperAuthTicketUrl()
		{
			var url = "/api/commerce/customer/authtickets/anonymousshopper";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			return mozuUrl;
		}

				/// <summary>
        /// Get Resource Url for CreateUserAuthTicket
        /// </summary>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl CreateUserAuthTicketUrl()
		{
			var url = "/api/commerce/customer/authtickets/";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			return mozuUrl;
		}

				/// <summary>
        /// Get Resource Url for RefreshUserAuthTicket
        /// </summary>
        /// <param name="refreshToken"></param>
        /// <returns>
        /// String - Resource Url
        /// </returns>
        public static MozuUrl RefreshUserAuthTicketUrl(string refreshToken)
		{
			var url = "/api/commerce/customer/authtickets/refresh?refreshToken={refreshToken}";
			var mozuUrl = new MozuUrl(url, MozuUrl.UrlLocation.TENANT_POD, false) ;
			mozuUrl.FormatUrl( "refreshToken", refreshToken);
			return mozuUrl;
		}

				
	}
}

