
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Contracts.Customer
{
		///
		///	The information required to modify a shopper account password.
		///
		public class PasswordInfo
		{
			///
			///The External Password, typically used for imports in conjunction with a custom action
			///
			public string ExternalPassword { get; set; }

			///
			///The new password entered and saved by the user of the account. 
			///
			public string NewPassword { get; set; }

			///
			///The previous shopper account password value.
			///
			public string OldPassword { get; set; }

		}

}