
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Mozu.Api.Contracts.CommerceRuntime.Returns
{
		///
		///	The reason for which the item is returned. Valid values include Damaged, Defective, MissingParts, DifferentExpectations, Late, NoLongerWanted, or Other.
		///
		public class ReturnReason
		{
			///
			///The quantity of the item returned for the specified reason.
			///
			public int Quantity { get; set; }

			///
			///The reason for which an item is returned to the merchant.
			///
			public string Reason { get; set; }

		}

}