
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Contracts.SiteSettings.General
{
		///
		///	Mozu.SiteSettings.General.Contracts.EmailTransactionSettings ApiType DOCUMENT_HERE 
		///
		public class EmailTransactionSettings
		{
			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings backInStock ApiTypeMember DOCUMENT_HERE 
			///
			public bool? BackInStock { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings giftCardCreated ApiTypeMember DOCUMENT_HERE 
			///
			public bool? GiftCardCreated { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings orderChanged ApiTypeMember DOCUMENT_HERE 
			///
			public bool? OrderChanged { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings orderFulfillmentDetailsChanged ApiTypeMember DOCUMENT_HERE 
			///
			public bool? OrderFulfillmentDetailsChanged { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings orderShipped ApiTypeMember DOCUMENT_HERE 
			///
			public bool? OrderShipped { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings refundCreated ApiTypeMember DOCUMENT_HERE 
			///
			public bool? RefundCreated { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings returnAuthorized ApiTypeMember DOCUMENT_HERE 
			///
			public bool? ReturnAuthorized { get; set; }

			///
			///There is no corresponding template for this in the Core theme.
			///
			public bool? ReturnCancelled { get; set; }

			///
			///This controls "email/product-return-received" in the Core theme.
			///
			public bool? ReturnClosed { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings returnCreated ApiTypeMember DOCUMENT_HERE 
			///
			public bool? ReturnCreated { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings returnRejected ApiTypeMember DOCUMENT_HERE 
			///
			public bool? ReturnRejected { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings returnUpdated ApiTypeMember DOCUMENT_HERE 
			///
			public bool? ReturnUpdated { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings shopperLoginCreated ApiTypeMember DOCUMENT_HERE 
			///
			public bool? ShopperLoginCreated { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings shopperPasswordReset ApiTypeMember DOCUMENT_HERE 
			///
			public bool? ShopperPasswordReset { get; set; }

			///
			///Mozu.SiteSettings.General.Contracts.EmailTransactionSettings storeCreditCreated ApiTypeMember DOCUMENT_HERE 
			///
			public bool? StoreCreditCreated { get; set; }

			///
			///The corresponding topic is not currently used by Mozu.
			///
			public bool? StoreCreditUpdated { get; set; }

		}

}