
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozu.Api
{
	public class Version
	{
		public static string ApiVersion
		{
			get { return "1.7.14119.0"; }
		}
	}
}