//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region Usings Setup

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net;
using Mozu.Api;
using Mozu.Api.Security;
using Mozu.Api.Test.Helpers;
using System.Diagnostics;

#endregion

namespace Mozu.Api.Test.Factories
{
	/// <summary>
	/// Use the Address Validation resource to validate addresses associated with a customer account contact.
	/// </summary>
	public partial class AddressValidationRequestFactory : BaseDataFactory
	{

		/// <summary> 
		/// Validates the customer address supplied in the request.
		/// <example> 
		///  <code> 
		/// var result = AddressValidationRequestFactory.ValidateAddress(handler : handler,  addressValidationRequest :  addressValidationRequest,  expectedCode: expectedCode, successCode: successCode); 
		/// var optionalCasting = ConvertClass<AddressValidationResponse/>(result); 
		/// return optionalCasting;
		///  </code> 
		/// </example> 
		/// </summary>
		public static Mozu.Api.Contracts.Customer.AddressValidationResponse ValidateAddress(ServiceClientMessageHandler handler, 
 		 Mozu.Api.Contracts.Customer.AddressValidationRequest addressValidationRequest, 
		 HttpStatusCode expectedCode = HttpStatusCode.OK, HttpStatusCode successCode = HttpStatusCode.OK)
		{
			SetSdKparameters();
			var currentClassName = System.Reflection.MethodInfo.GetCurrentMethod().DeclaringType.Name;
			var currentMethodName = System.Reflection.MethodBase.GetCurrentMethod().Name;
			Debug.WriteLine(currentMethodName  + '.' + currentMethodName );
			var apiClient = Mozu.Api.Clients.Commerce.Customer.AddressValidationRequestClient.ValidateAddressClient(
				 addressValidationRequest :  addressValidationRequest		);
			try
			{
				apiClient.WithContext(handler.ApiContext).Execute();
			}
			catch (ApiException ex)
			{
				// Custom error handling for test cases can be placed here
				Exception customException = TestFailException.GetCustomTestException(ex, currentClassName, currentMethodName, expectedCode);
				if (customException != null)
					throw customException;
				return null;
			}
			return ResponseMessageFactory.CheckResponseCodes(apiClient.HttpResponse.StatusCode, expectedCode, successCode) 
					 ? (apiClient.Result()) 
					 : null;

		}
  

	}

}


