
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Mozu.Api.Contracts.ProductAdmin
{
		///
		///	Properties of an individual vocabulary value for an attribute. For example, a "color" attribute might have the following vocabulary values: Red, Blue, Green.
		///
		public class AttributeVocabularyValue
		{
			///
			///The actual vocabulary value.
			///
			public object Value { get; set; }

			///
			///The number that denotes the order of the entity value within a list of entity values.
			///
			public int? ValueSequence { get; set; }

			///
			///Complex type that contains content for a language specified by LocaleCode.
			///
			public AttributeVocabularyValueLocalizedContent Content { get; set; }

		}

}