
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Mozu.Api.Security;


namespace Mozu.Api.Resources.Commerce.Customer.Accounts
{
	/// <summary>
	/// Use the Customer Account Transactions resource to manage the transactions associated with a customer account.
	/// </summary>
	public partial class TransactionResource  	{
		///
		/// <see cref="Mozu.Api.ApiContext"/>
		///
		private readonly IApiContext _apiContext;

		public TransactionResource(IApiContext apiContext) 
		{
			_apiContext = apiContext;
		}

		
		/// <summary>
		/// Retrieves a list of transactions associated with the customer account specified in the request.
		/// </summary>
		/// <param name="accountId">Unique identifier of the customer account for which to retrieve transactions.</param>
		/// <returns>
		/// List{<see cref="Mozu.Api.Contracts.Customer.Transaction"/>}
		/// </returns>
		/// <example>
		/// <code>
		///   var transaction = new Transaction();
		///   var transaction = transaction.GetTransactions( accountId);
		/// </code>
		/// </example>
		public virtual List<Mozu.Api.Contracts.Customer.Transaction> GetTransactions(int accountId)
		{
			MozuClient<List<Mozu.Api.Contracts.Customer.Transaction>> response;
			var client = Mozu.Api.Clients.Commerce.Customer.Accounts.TransactionClient.GetTransactionsClient( accountId);
			client.WithContext(_apiContext);
			response= client.Execute();
			return response.Result();

		}

		/// <summary>
		/// Creates a new transaction for the customer account specified in the request.
		/// </summary>
		/// <param name="accountId">Unique identifier of the customer account.</param>
		/// <param name="transaction">Properties of the transaction to create for the customer account.</param>
		/// <returns>
		/// <see cref="Mozu.Api.Contracts.Customer.Transaction"/>
		/// </returns>
		/// <example>
		/// <code>
		///   var transaction = new Transaction();
		///   var transaction = transaction.AddTransaction( transaction,  accountId);
		/// </code>
		/// </example>
		public virtual Mozu.Api.Contracts.Customer.Transaction AddTransaction(Mozu.Api.Contracts.Customer.Transaction transaction, int accountId)
		{
			MozuClient<Mozu.Api.Contracts.Customer.Transaction> response;
			var client = Mozu.Api.Clients.Commerce.Customer.Accounts.TransactionClient.AddTransactionClient( transaction,  accountId);
			client.WithContext(_apiContext);
			response= client.Execute();
			return response.Result();

		}

		/// <summary>
		/// Deletes a transaction from the customer account specified in the request.
		/// </summary>
		/// <param name="accountId">Unique identifier of the customer account from which to delete the transaction.</param>
		/// <param name="transactionId">Unique identifier of the transaction to delete.</param>
		/// <returns>
		/// 
		/// </returns>
		/// <example>
		/// <code>
		///   var transaction = new Transaction();
		///   transaction.RemoveTransaction( accountId,  transactionId);
		/// </code>
		/// </example>
		public virtual void RemoveTransaction(int accountId, string transactionId)
		{
			MozuClient response;
			var client = Mozu.Api.Clients.Commerce.Customer.Accounts.TransactionClient.RemoveTransactionClient( accountId,  transactionId);
			client.WithContext(_apiContext);
			response= client.Execute();

		}


	}

}


