
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Contracts.AppDev
{
		///
		///	Mozu.AppDev.Contracts.ApplicationBehavior ApiType DOCUMENT_HERE 
		///
		public class ApplicationBehavior
		{
			///
			///Mozu.AppDev.Contracts.ApplicationBehavior behaviorId ApiTypeMember DOCUMENT_HERE 
			///
			public int BehaviorId { get; set; }

			///
			///Mozu.AppDev.Contracts.ApplicationBehavior packageId ApiTypeMember DOCUMENT_HERE 
			///
			public int PackageId { get; set; }

		}

}