
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Codezu.     
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;


namespace Mozu.Api.Contracts.ProductAdmin
{
		///
		///	The price of the product in the specified currency code (USD). This price can either be the sale price or the price for which the merchang intends to sell the product.
		///
		public class ProductPrice
		{
			///
			///The credit value of the product or bundled product. When the `goodsType `is `DigitalCredit`, this value is populated to indicate the value of the credit. This is used to create store credit in the fulfillment of gift cards.
			///
			public decimal? CreditValue { get; set; }

			///
			///3-letter ISO 4217 standard global currency code. Currently, only "USD" (US Dollar) is supported.
			///
			public string IsoCurrencyCode { get; set; }

			///
			///The minimum advertised price a client can charge for the associated product, as determined by the supplier. Client administrators can override the minimum advertised price at the catalog level.
			///
			public decimal? Map { get; set; }

			///
			///If the product has a supplier-defined minimum advertised price, the date and time after which the client can sell the product for less than the minimum advertised price.
			///
			public DateTime? MapEndDate { get; set; }

			///
			///If the product has a supplier-defined minimum advertised price, the date and time after which the client cannot sell the product for less than the minimum advertised price.
			///
			public DateTime? MapStartDate { get; set; }

			///
			///The manufacturer's suggested retail price for the product. This content may be defined by the supplier.
			///
			public decimal? Msrp { get; set; }

			///
			///Price that the merchant intends to sell the product which is not necessarily the list price. This is the price the merchant intends to sell the product if no sale price is present.
			///
			public decimal? Price { get; set; }

			///
			///The set sale price for a product consisting of a price with a discount already applied.
			///
			public decimal? SalePrice { get; set; }

		}

}